# Generated by Django 6.0.1 on 2026-01-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Enter the IP address allowed to access the Admin Panel.', unique=True, verbose_name='IP Address')),
                ('description', models.CharField(blank=True, help_text='e.g. Office PC, Server Room', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily disable access for this IP.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Allowed Admin IP',
                'verbose_name_plural': 'Allowed Admin IPs',
            },
        ),
    ]
