# Generated by Django 5.1.4 on 2026-01-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauseList', '0001_initial'),
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causelist',
            name='title',
        ),
        migrations.AddField(
            model_name='causelist',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approve to make this cause list visible on the frontend.'),
        ),
        migrations.AddField(
            model_name='causelist',
            name='title_en',
            field=models.CharField(default='Default Title', help_text='e.g., Cause List for 12th Jan 2025 (English)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='causelist',
            name='title_sd',
            field=models.CharField(blank=True, help_text='Title in Sindhi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='causelist',
            name='title_ur',
            field=models.CharField(blank=True, help_text='Title in Urdu', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='causelist',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a PDF/image file for the cause list (if not generating from hearings).', null=True, upload_to='cause_lists/'),
        ),
        migrations.AlterField(
            model_name='causelist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CauseListHearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('cause_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CauseList.causelist')),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.hearing')),
            ],
            options={
                'verbose_name': 'Hearing in Cause List',
                'verbose_name_plural': 'Hearings in Cause List',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='causelist',
            name='hearings',
            field=models.ManyToManyField(blank=True, related_name='cause_lists', through='CauseList.CauseListHearing', to='complaint.hearing', verbose_name='Associated Hearings'),
        ),
    ]
