# Generated by Django 5.1.4 on 2026-01-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauseList', '0003_cleanup_old_hearings_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='causelisthearing',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial No.'),
        ),
    ]
