# Generated by Django 5.1.4 on 2026-01-19 21:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ur', models.CharField(blank=True, max_length=255, verbose_name='Title (Urdu)')),
                ('title_sd', models.CharField(blank=True, max_length=255, verbose_name='Title (Sindhi)')),
                ('description_en', ckeditor.fields.RichTextField(verbose_name='Description (English)')),
                ('description_ur', ckeditor.fields.RichTextField(blank=True, verbose_name='Description (Urdu)')),
                ('description_sd', ckeditor.fields.RichTextField(blank=True, verbose_name='Description (Sindhi)')),
                ('file', models.FileField(upload_to='budget_files/', verbose_name='Budget File (PDF/Image)')),
                ('is_approved', models.BooleanField(default=False, help_text='Approve to display this budget on the frontend.', verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-created_at'],
            },
        ),
    ]
