# Generated by Django 5.1.4 on 2026-01-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SICBudgetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='expenditure_data',
            field=models.JSONField(blank=True, help_text='JSON Format: [{"label": "Salaries", "value": 50000}, {"label": "Development", "value": 20000}]', null=True, verbose_name='Expenditure Data'),
        ),
    ]
