# Generated by Django 5.1.4 on 2026-01-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SICBudgetApp', '0002_budget_expenditure_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='amount_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount Balance/Lapsed'),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_grant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Grant in Aid Received'),
        ),
    ]
