# Generated by Django 6.0.1 on 2026-01-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commissioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('is_chief', models.BooleanField(default=False, verbose_name='Is Chief Commissioner?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='commissioners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_chief', 'created_at'],
            },
        ),
    ]
