# Generated by Django 6.0.1 on 2026-01-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissioners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissioner',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='commissioner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='commissioner',
            name='title',
        ),
        migrations.AddField(
            model_name='commissioner',
            name='bio_en',
            field=models.TextField(default='', verbose_name='Bio (English)'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='bio_sd',
            field=models.TextField(default='', verbose_name='Bio (Sindhi)'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='bio_ur',
            field=models.TextField(default='', verbose_name='Bio (Urdu)'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='name_sd',
            field=models.CharField(default='', max_length=255, verbose_name='Name (Sindhi)'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='name_ur',
            field=models.CharField(default='', max_length=255, verbose_name='Name (Urdu)'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='title_en',
            field=models.CharField(default='', max_length=255, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='title_sd',
            field=models.CharField(default='', max_length=255, verbose_name='Title (Sindhi)'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='title_ur',
            field=models.CharField(default='', max_length=255, verbose_name='Title (Urdu)'),
        ),
    ]
