# Generated by Django 6.0.1 on 2026-01-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissioners', '0002_remove_commissioner_bio_remove_commissioner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioner',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='education_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Highest Education (English)'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='education_sd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Highest Education (Sindhi)'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='education_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Highest Education (Urdu)'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
