# Generated by Django 5.1.4 on 2026-01-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissioners', '0003_commissioner_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissioner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
