# Generated by Django 6.0.1 on 2026-01-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Job Title (English)')),
                ('title_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title (Urdu)')),
                ('title_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title (Sindhi)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('description_ur', models.TextField(blank=True, null=True, verbose_name='Description (Urdu)')),
                ('description_sd', models.TextField(blank=True, null=True, verbose_name='Description (Sindhi)')),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='careers/', verbose_name='Advertisement/Details PDF')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Apply Link')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
