# Generated by Django 6.0.1 on 2026-01-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title for the document', max_length=255)),
                ('resource_type', models.CharField(choices=[('ACT', 'Sindh Transparency & RTI Act, 2016'), ('RULES', 'Rules of Business 2017'), ('GUIDE', "Citizen's Guide to RTI"), ('FORM_A', 'Form A (Information Request)'), ('FORM_B', 'Form B (Internal Review)'), ('FORM_C', 'Form C (Appeal)')], max_length=20, unique=True)),
                ('file_en', models.FileField(blank=True, null=True, upload_to='resources/en/', verbose_name='English PDF')),
                ('file_ur', models.FileField(blank=True, null=True, upload_to='resources/ur/', verbose_name='Urdu PDF')),
                ('file_sd', models.FileField(blank=True, null=True, upload_to='resources/sd/', verbose_name='Sindhi PDF')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Law & Resource Document',
            },
        ),
    ]
