# Generated by Django 6.0.1 on 2026-01-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Urdu)')),
                ('title_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Sindhi)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('description_ur', models.TextField(blank=True, null=True, verbose_name='Description (Urdu)')),
                ('description_sd', models.TextField(blank=True, null=True, verbose_name='Description (Sindhi)')),
                ('notification_type', models.CharField(choices=[('notification', 'Notification'), ('event', 'Event')], default='notification', max_length=20)),
                ('event_date', models.DateTimeField(blank=True, help_text='Required for Events', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='notifications/')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
