# Generated by Django 5.1.4 on 2026-01-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview_text_en', models.TextField(verbose_name='Overview Text (English)')),
                ('overview_text_ur', models.TextField(blank=True, verbose_name='Overview Text (Urdu)')),
                ('overview_text_sd', models.TextField(blank=True, verbose_name='Overview Text (Sindhi)')),
                ('mission_title_en', models.CharField(default='Our Mission', max_length=255, verbose_name='Mission Title (English)')),
                ('mission_title_ur', models.CharField(blank=True, max_length=255, verbose_name='Mission Title (Urdu)')),
                ('mission_title_sd', models.CharField(blank=True, max_length=255, verbose_name='Mission Title (Sindhi)')),
                ('mission_desc_en', models.TextField(verbose_name='Mission Description (English)')),
                ('mission_desc_ur', models.TextField(blank=True, verbose_name='Mission Description (Urdu)')),
                ('mission_desc_sd', models.TextField(blank=True, verbose_name='Mission Description (Sindhi)')),
                ('powers_title_en', models.CharField(default='Appellate Powers', max_length=255, verbose_name='Powers Title (English)')),
                ('powers_title_ur', models.CharField(blank=True, max_length=255, verbose_name='Powers Title (Urdu)')),
                ('powers_title_sd', models.CharField(blank=True, max_length=255, verbose_name='Powers Title (Sindhi)')),
                ('powers_desc_en', models.TextField(verbose_name='Powers Description (English)')),
                ('powers_desc_ur', models.TextField(blank=True, verbose_name='Powers Description (Urdu)')),
                ('powers_desc_sd', models.TextField(blank=True, verbose_name='Powers Description (Sindhi)')),
                ('is_active', models.BooleanField(default=True, help_text='Set to true to display this overview on the dashboard.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Overview',
                'verbose_name_plural': 'Commission Overviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
