# Generated by Django 5.1.4 on 2026-01-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommissionOverviewApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionoverview',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='commission_overview/', verbose_name='Dashboard Background Image'),
        ),
    ]
