# Generated by Django 5.1.4 on 2026-01-19 04:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommissionOverviewApp', '0002_commissionoverview_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionoverview',
            name='overview_text_en',
            field=ckeditor.fields.RichTextField(verbose_name='Overview Text (English)'),
        ),
        migrations.AlterField(
            model_name='commissionoverview',
            name='overview_text_sd',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Overview Text (Sindhi)'),
        ),
        migrations.AlterField(
            model_name='commissionoverview',
            name='overview_text_ur',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Overview Text (Urdu)'),
        ),
    ]
