# Generated by Django 5.1.4 on 2026-01-19 04:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommissionOverviewApp', '0003_alter_commissionoverview_overview_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionoverview',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='mission_desc_en',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='mission_desc_sd',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='mission_desc_ur',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='mission_title_en',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='mission_title_sd',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='mission_title_ur',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='overview_text_en',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='overview_text_sd',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='overview_text_ur',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='powers_desc_en',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='powers_desc_sd',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='powers_desc_ur',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='powers_title_en',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='powers_title_sd',
        ),
        migrations.RemoveField(
            model_name='commissionoverview',
            name='powers_title_ur',
        ),
        migrations.AddField(
            model_name='commissionoverview',
            name='description_en',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Description (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionoverview',
            name='description_sd',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description (Sindhi)'),
        ),
        migrations.AddField(
            model_name='commissionoverview',
            name='description_ur',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description (Urdu)'),
        ),
        migrations.AddField(
            model_name='commissionoverview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='commission_overview/', verbose_name='Overview Image'),
        ),
        migrations.AddField(
            model_name='commissionoverview',
            name='title_en',
            field=models.CharField(default='Commission Overview', max_length=255, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='commissionoverview',
            name='title_sd',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Sindhi)'),
        ),
        migrations.AddField(
            model_name='commissionoverview',
            name='title_ur',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Urdu)'),
        ),
    ]
