# Generated by Django 6.0.1 on 2026-01-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Website Logo', max_length=100)),
                ('logo_image', models.ImageField(help_text='Upload the website logo. Recommended size: 200x50 pixels.', upload_to='website_settings/logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Set this as the currently active logo for the website. Only one can be active.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Website Logo',
                'verbose_name_plural': 'Website Logos',
            },
        ),
    ]