# Generated by Django 6.0.1 on 2026-01-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Urdu)')),
                ('name_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Sindhi)')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='Address (English)')),
                ('address_ur', models.TextField(blank=True, null=True, verbose_name='Address (Urdu)')),
                ('address_sd', models.TextField(blank=True, null=True, verbose_name='Address (Sindhi)')),
                ('pio_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIO Name (English)')),
                ('pio_name_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIO Name (Urdu)')),
                ('pio_name_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIO Name (Sindhi)')),
                ('pio_designation_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIO Designation (English)')),
                ('pio_designation_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIO Designation (Urdu)')),
                ('pio_designation_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIO Designation (Sindhi)')),
                ('pio_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='PIO Contact Number')),
                ('pio_address_en', models.TextField(blank=True, null=True, verbose_name='PIO Address (English)')),
                ('pio_address_ur', models.TextField(blank=True, null=True, verbose_name='PIO Address (Urdu)')),
                ('pio_address_sd', models.TextField(blank=True, null=True, verbose_name='PIO Address (Sindhi)')),
                ('hod_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Name (English)')),
                ('hod_name_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Name (Urdu)')),
                ('hod_name_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Name (Sindhi)')),
                ('hod_designation_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Designation (English)')),
                ('hod_designation_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Designation (Urdu)')),
                ('hod_designation_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Designation (Sindhi)')),
                ('hod_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='HOD Contact Number')),
                ('hod_address_en', models.TextField(blank=True, null=True, verbose_name='HOD Address (English)')),
                ('hod_address_ur', models.TextField(blank=True, null=True, verbose_name='HOD Address (Urdu)')),
                ('hod_address_sd', models.TextField(blank=True, null=True, verbose_name='HOD Address (Sindhi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Public Body',
                'verbose_name_plural': 'Public Bodies',
                'ordering': ['name_en'],
            },
        ),
    ]
