# Generated by Django 5.1.4 on 2026-01-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicBodies', '0002_alter_publicbody_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicbody',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='publicbody',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='publicbody',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website URL'),
        ),
    ]
