# Generated by Django 5.1.4 on 2026-01-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicBodies', '0003_publicbody_email_publicbody_phone_publicbody_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicbody',
            name='hod_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='HOD Email Address'),
        ),
        migrations.AddField(
            model_name='publicbody',
            name='pio_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='PIO Email Address'),
        ),
    ]
