# Generated by Django 5.1.4 on 2026-01-21 04:10

import django.db.models.deletion
from django.db import migrations, models

def create_default_department(apps, schema_editor):
    Department = apps.get_model('publicBodies', 'Department')
    Department.objects.create(
        id=1, 
        name_en="General Administration Department",
        name_ur="جنرل ایڈمنسٹریشن ڈیپارٹمنٹ",
        name_sd="جنرل ايڊمنسٽريشن ڊپارٽمينٽ"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('publicBodies', '0004_publicbody_hod_email_publicbody_pio_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Department Name (English)')),
                ('name_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Department Name (Urdu)')),
                ('name_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Department Name (Sindhi)')),
                ('hod_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Name (English)')),
                ('hod_name_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Name (Urdu)')),
                ('hod_name_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Name (Sindhi)')),
                ('hod_designation_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Designation (English)')),
                ('hod_designation_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Designation (Urdu)')),
                ('hod_designation_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='HOD Designation (Sindhi)')),
                ('hod_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='HOD Contact Number')),
                ('hod_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='HOD Email Address')),
                ('hod_address_en', models.TextField(blank=True, null=True, verbose_name='HOD Address (English)')),
                ('hod_address_ur', models.TextField(blank=True, null=True, verbose_name='HOD Address (Urdu)')),
                ('hod_address_sd', models.TextField(blank=True, null=True, verbose_name='HOD Address (Sindhi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Administrative Department',
                'verbose_name_plural': 'Administrative Departments',
                'ordering': ['name_en'],
            },
        ),
        # This line ensures the department exists before we try to link to it
        migrations.RunPython(create_default_department),
        migrations.RemoveField(
            model_name='publicbody',
            name='hod_address_en',
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='hod_address_sd',
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='hod_address_ur',
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='hod_contact',
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='hod_designation_en',
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='hod_designation_sd',
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='hod_designation_ur',
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='hod_email',
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='hod_name_en',
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='hod_name_sd',
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='hod_name_ur',
        ),
        migrations.AlterField(
            model_name='publicbody',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Public Body Name (English)'),
        ),
        migrations.AddField(
            model_name='publicbody',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='public_bodies', to='publicBodies.department', verbose_name='Parent Department'),
            preserve_default=False,
        ),
    ]
