# Generated by Django 6.0.1 on 2026-01-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicBodies', '0006_alter_department_id_alter_publicbody_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department Contact Number'),
        ),
    ]
