# Generated by Django 6.0.1 on 2026-01-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicBodies', '0007_department_department_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name_en'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
