# Generated by Django 5.1.4 on 2026-01-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sindh Transparency & Right to Information Act, 2016', max_length=255)),
                ('pdf_file', models.FileField(upload_to='acts/', verbose_name='Act PDF')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active act will be displayed on the dashboard.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
