# Generated by Django 6.0.1 on 2026-01-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoDeskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Urdu)')),
                ('title_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Sindhi)')),
                ('category', models.CharField(choices=[('tenders', 'Advertisement and Tender'), ('pio-guidelines', 'PIO Guideline'), ('proactive-disclosures', 'Proactive Disclosure'), ('publications', 'Publication')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='infodesk/')),
                ('link', models.URLField(blank=True, help_text='External link if no file is uploaded', null=True)),
                ('publication_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Info Desk Document',
                'ordering': ['-publication_date'],
            },
        ),
    ]
