# Generated by Django 6.0.1 on 2026-01-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoDesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infodeskdocument',
            name='category',
            field=models.CharField(choices=[('advertisements', 'Advertisement'), ('tenders', 'Tender'), ('pio-guidelines', 'PIO Guideline'), ('proactive-disclosures', 'Proactive Disclosure'), ('publications', 'Publication')], max_length=50),
        ),
    ]
