# Generated by Django 6.0.1 on 2026-01-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organogram',
            name='title',
        ),
        migrations.AddField(
            model_name='organogram',
            name='title_en',
            field=models.CharField(default='Organogram of Sindh Information Commission', max_length=255, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='organogram',
            name='title_sd',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Sindhi)'),
        ),
        migrations.AddField(
            model_name='organogram',
            name='title_ur',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Urdu)'),
        ),
    ]