# Generated by Django 6.0.1 on 2026-01-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Urdu)')),
                ('title_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Sindhi)')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('content_ur', models.TextField(blank=True, null=True, verbose_name='Content (Urdu)')),
                ('content_sd', models.TextField(blank=True, null=True, verbose_name='Content (Sindhi)')),
                ('social_media_link', models.URLField(blank=True, null=True, verbose_name='Social Media Link')),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='GalleryApp.event')),
            ],
        ),
    ]
