# Generated by Django 6.0.1 on 2026-01-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('department_en', models.CharField(max_length=255, verbose_name='Department (English)')),
                ('bio_en', models.TextField(verbose_name='Bio (English)')),
                ('education_en', models.TextField(verbose_name='Education (English)')),
                ('experience_en', models.TextField(verbose_name='Experience (English)')),
                ('name_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Urdu)')),
                ('title_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Urdu)')),
                ('department_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Department (Urdu)')),
                ('bio_ur', models.TextField(blank=True, null=True, verbose_name='Bio (Urdu)')),
                ('education_ur', models.TextField(blank=True, null=True, verbose_name='Education (Urdu)')),
                ('experience_ur', models.TextField(blank=True, null=True, verbose_name='Experience (Urdu)')),
                ('name_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Sindhi)')),
                ('title_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Sindhi)')),
                ('department_sd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Department (Sindhi)')),
                ('bio_sd', models.TextField(blank=True, null=True, verbose_name='Bio (Sindhi)')),
                ('education_sd', models.TextField(blank=True, null=True, verbose_name='Education (Sindhi)')),
                ('experience_sd', models.TextField(blank=True, null=True, verbose_name='Experience (Sindhi)')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which staff appears')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
