# Generated by Django 6.0.4 on 2026-04-10 07:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicBodies', '0008_alter_department_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('cnic', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('postal_address', models.TextField(verbose_name='Postal Address')),
                ('permanent_address', models.TextField(verbose_name='Permanent Address')),
                ('department', models.CharField(max_length=255)),
                ('custom_department', models.CharField(blank=True, max_length=255, null=True)),
                ('public_body_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Public Body (e.g. BHU, School)')),
                ('public_body_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Public Body Contact Number')),
                ('department_address', models.TextField(blank=True, null=True, verbose_name='Public Body Address')),
                ('pio_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pio_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('pio_address', models.TextField(blank=True, null=True)),
                ('hod_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hod_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('department_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department Contact Number')),
                ('hod_address', models.TextField(blank=True, null=True, verbose_name='Department Address')),
                ('initial_request_date', models.DateField(blank=True, null=True, verbose_name='Date of Initial Application to PIO')),
                ('request_submission_mode', models.CharField(choices=[('COURIER', 'Courier Service'), ('BY_HAND', 'By Hand')], default='COURIER', max_length=20, verbose_name='Request Submission Mode')),
                ('internal_review_date', models.DateField(blank=True, null=True, verbose_name='Date of Internal Review Application')),
                ('review_submission_mode', models.CharField(choices=[('COURIER', 'Courier Service'), ('BY_HAND', 'By Hand')], default='COURIER', max_length=20, verbose_name='Review Submission Mode')),
                ('subject', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('cnic_front', models.ImageField(blank=True, null=True, upload_to='complaints/cnic/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='CNIC Front')),
                ('cnic_back', models.ImageField(blank=True, null=True, upload_to='complaints/cnic/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='CNIC Back')),
                ('application_file', models.FileField(upload_to='complaints/application/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='First Application')),
                ('application_ack_file', models.FileField(blank=True, null=True, upload_to='complaints/application_ack/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Application Acknowledgement')),
                ('internal_review_file', models.FileField(upload_to='complaints/review/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Internal Review Application')),
                ('internal_review_ack_file', models.FileField(blank=True, null=True, upload_to='complaints/review_ack/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Internal Review Acknowledgement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('complaint_number', models.CharField(blank=True, help_text='e.g. 230', max_length=50, null=True)),
                ('complaint_year', models.CharField(blank=True, help_text='e.g. 2026', max_length=4, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Approve to make this complaint trackable by the public.', verbose_name='Administrative Approval')),
                ('sections_involved', models.CharField(blank=True, help_text='e.g. Section 6(3)', max_length=255, null=True)),
                ('filing_mode', models.CharField(choices=[('PORTAL', 'Online Portal'), ('COURIER', 'Courier Service'), ('BY_HAND', 'By Hand')], default='PORTAL', max_length=20, verbose_name='Complaint Filing Mode')),
                ('department_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicBodies.department', verbose_name='Select Department')),
                ('public_body_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicBodies.publicbody', verbose_name='Select Public Body')),
            ],
        ),
        migrations.CreateModel(
            name='NewComplaint',
            fields=[
            ],
            options={
                'verbose_name': 'Complaint Box',
                'verbose_name_plural': 'Complaint Box',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('complaint.complaint',),
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField(blank=True, null=True, verbose_name='Hearing Date')),
                ('hearing_time', models.TimeField(blank=True, null=True, verbose_name='Hearing Time')),
                ('complainant_name', models.CharField(blank=True, help_text='Override if different from Complaint', max_length=255)),
                ('respondent_name', models.CharField(blank=True, help_text='Official appearing for the department', max_length=255)),
                ('complainant_is_present', models.BooleanField(default=True, verbose_name='Complainant Present')),
                ('respondent_is_present', models.BooleanField(default=True, verbose_name='Respondent Present')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bench_members', models.CharField(blank=True, help_text='Commissioners hearing the case', max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number from Cause List', max_length=50, null=True)),
                ('procedural_status', models.CharField(blank=True, choices=[('FIRST_NOTICE', 'First Notice'), ('FINAL_NOTICE', 'Final Notice'), ('SHOW_CAUSE', 'Show Cause Notice'), ('FINAL_SHOW_CAUSE', 'Final Show Cause Notice'), ('TEN_DAYS_ORDER', 'Ten Days Order'), ('PENALTY_ORDER', 'Penalty Order'), ('ADJOURNMENT', 'Adjournment Order'), ('RECALL', 'Recall Order'), ('FURTHER_PROCEEDINGS', 'Further Proceedings'), ('DISPOSED_OFF', 'Disposed-off'), ('NON_MAINTAINABLE', 'Complaint Non-Maintainable')], max_length=100, null=True, verbose_name='Proceedings Status')),
                ('disposal_reason', models.CharField(blank=True, choices=[('INFO_PROVIDED', 'Information/Record Provided'), ('NON_MAINTAINABLE', 'Complaint Non-Maintainable'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Reason for Disposal')),
                ('info_provided_file', models.FileField(blank=True, null=True, upload_to='complaints/status/info/', verbose_name='Information Provided Order')),
                ('first_notice_file', models.FileField(blank=True, null=True, upload_to='complaints/status/notice1/', verbose_name='First Notice')),
                ('final_notice_file', models.FileField(blank=True, null=True, upload_to='complaints/status/notice2/', verbose_name='Final Notice')),
                ('show_cause_file', models.FileField(blank=True, null=True, upload_to='complaints/status/show_cause/', verbose_name='Show Cause Notice')),
                ('final_show_cause_file', models.FileField(blank=True, null=True, upload_to='complaints/status/final_show_cause/', verbose_name='Final Show Cause Notice')),
                ('ten_days_order_file', models.FileField(blank=True, null=True, upload_to='complaints/status/ten_days/', verbose_name='Ten Days Order')),
                ('penalty_order_file', models.FileField(blank=True, null=True, upload_to='complaints/status/penalty/', verbose_name='Penalty Order')),
                ('adjournment_file', models.FileField(blank=True, null=True, upload_to='complaints/status/adjournment/', verbose_name='Adjournment Order')),
                ('recall_file', models.FileField(blank=True, null=True, upload_to='complaints/status/recall/', verbose_name='Recall Order')),
                ('further_proceedings_file', models.FileField(blank=True, null=True, upload_to='complaints/status/further/', verbose_name='Further Proceedings Order')),
                ('disposed_off_file', models.FileField(blank=True, null=True, upload_to='complaints/status/disposed/', verbose_name='Disposal Order')),
                ('non_maintainable_file', models.FileField(blank=True, null=True, upload_to='complaints/status/non_maintainable/', verbose_name='Non-Maintainable Order')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='complaint.complaint')),
            ],
            options={
                'ordering': ['-hearing_date', '-hearing_time'],
            },
        ),
    ]
