# Generated by Django 6.0.1 on 2026-01-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Total Requests')),
                ('appeals_filed', models.IntegerField(default=0, verbose_name='Appeals Filed')),
                ('resolved_cases', models.IntegerField(default=0, verbose_name='Resolved Cases')),
                ('avg_response_time', models.IntegerField(default=0, verbose_name='Average Response Time (Days)')),
                ('requests_trend', models.CharField(default='+0%', help_text='e.g. +12%', max_length=50)),
                ('appeals_trend', models.CharField(default='+0%', help_text='e.g. +5%', max_length=50)),
                ('resolved_trend', models.CharField(default='+0%', help_text='e.g. +8%', max_length=50)),
                ('annual_report', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Annual Report PDF')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Statistic',
                'verbose_name_plural': 'Dashboard Statistics',
            },
        ),
    ]
