# Generated by Django 6.0.1 on 2026-01-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_dashboardstat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardstat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
